sudo: required

env:
  - VERSION=9.3
  - VERSION=9.4

services:
  - docker

before_install:
  - docker build -t nanobox/nanobox-docker-postgresql:$VERSION ./$VERSION

script: sudo test/run_all.sh $VERSION