sudo: required

env:
  - VERSION=9.3
  - VERSION=9.4

services:
  - docker

before_install:
  - docker build -t nanobox/nanobox-docker-postgresql:$VERSION -f Dockerfile-$VERSION .
  - docker tag -f nanobox/nanobox-docker-postgresql:$VERSION nanobox/nanobox-docker-postgresql:$VERSION-alpha


script: sudo tests/run.sh $VERSION

after_success:
  - echo push nanobox/nanobox-docker-postgresql:$VERSION-alpha