sudo: required

services:
  - docker

before_install:
  - docker build -t nanobox/nanobox-docker-postgresql:9.3 -f Dockerfile-9.3 .
  - docker build -t nanobox/nanobox-docker-postgresql:9.4 -f Dockerfile-9.4 .


script: sudo tests/run.sh